language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true

script:
  - >
    echo;
    echo "Running unit tests";
    mkdir -p build/logs;
    if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; else PHPUNIT_FLAGS=""; fi ;
    php vendor/bin/phpunit --colors $PHPUNIT_FLAGS ;

after_script:
  - >
    if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml ; fi;
